---
apiVersion: v1
kind: Namespace
metadata:
  name: sushiweb-cli
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: sushiweb
  namespace: sushiweb-cli
spec:
  type: Git
  pathname: https://github.com/narjisse/rhacm.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: sushiweb-placement-1
  namespace: sushiweb-cli
spec:
  clusterSelector:
    matchLabels:
      sushi: 'true' 
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: sushiweb
  namespace: sushiweb-cli
  labels:
    app: sushiweb-app
  annotations:
    apps.open-cluster-management.io/github-path: sushiweb/sushiweb-resources
spec:
  channel: sushiweb-cli/sushiweb
  placement:
    placementRef:
      kind: PlacementRule
      name: sushiweb-placement-1
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: sushiweb-app
  namespace: sushiweb-cli
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - sushiweb
