---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: sushiweb
  namespace: sushiweb-cli
  labels:
    app: sushiweb
  annotations:sushiweb-resources
    apps.open-cluster-management.io/github-path: sushiweb/sushiweb-resources
spec:
  channel: sushiweb-cli/sushiweb
  placement:
    placementRef:
      kind: PlacementRule
      name: sushiweb-placement-1
