---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: sushiweb-subscription-1
  namespace: sushiweb-cli
  labels:
    app: sushiweb
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: sushiweb/sushiweb-resources
    apps.open-cluster-management.io/reconcile-option: merge  
spec:
  channel: ggithubcom-narjisse-rhacm-ns/ggithubcom-narjisse-rhacm
  placement:
    placementRef:
      kind: PlacementRule
      name: sushiweb-placement-1
